"""
migrate_drill_layout.py — one-off: move the sibling drills project to the
per-language layout and rename the Java drills to the language-prefixed scheme.

Run once, when the drill system gained a second language. Idempotent and
re-runnable: every step checks whether it has already been done.

WHAT IT DOES
    1. Moves `pom.xml`, `src/` and `target/` into `java/`, so Java and Python
       each own a subdirectory of MANUAL_CODE_DRILLS_DIR. `pom.xml` needs no
       edit — it uses the standard Maven layout with no <sourceDirectory>
       override, so it keeps working from its new home.
    2. Creates `python/` with a README on running pytest.
    3. Renames `Drill<N>.java` -> `JavaDrill<N>.java` and
       `Drill<N>Test.java` -> `JavaDrill<N>Test.java`, rewriting the class
       identifiers and every cross-file reference inside them. Java requires the
       public class name to match the filename, so the rename and the identifier
       rewrite are the same operation — doing one without the other leaves a
       project that doesn't compile.
    4. Rewrites the SAME identifiers inside `data/drills.json`, in each part's
       stored `attempt` snapshot and `solution` text. This is the step that is
       easy to miss and expensive to skip:
         * `attempt` is what `drills.revert_part` writes back over the installed
           reference. A snapshot still saying `class Drill9` restored into
           `JavaDrill9.java` produces a file that does not compile — so the undo
           would be broken rather than merely stale.
         * `solution` text is handed to the reviewer as the "baseline you were
           GIVEN" from part 2 on. If it names a class the file no longer
           declares, the reviewer is comparing against the wrong thing.
       Historical `feedback` prose is deliberately left alone — it is a record of
       what was said at the time, not something anything reads back as code.

Default is a DRY RUN. Nothing is touched until `--apply`.

Usage:
    python scripts/migrate_drill_layout.py            # dry run
    python scripts/migrate_drill_layout.py --apply
"""

import argparse
import re
import shutil
import sys
from pathlib import Path

from config import (
    DRILLS_STORE_PATH,
    MANUAL_CODE_DRILLS_DIR,
    drill_lang,
    drill_language_of,
    load_drills,
    save_drills,
)

# `Drill12` and `Drill12Test` both start with `Drill<digits>`, so one pattern
# covers both — there is no trailing \b, because `Drill8Test` has no boundary
# after the 8. The negative lookbehind on "Java" is what makes the script
# re-runnable: an already-migrated `JavaDrill8` must not become
# `JavaJavaDrill8`. The lookbehind on word characters stops it matching inside
# some other identifier that merely ends in "Drill".
_IDENT_RE = re.compile(r"(?<!Java)(?<![A-Za-z0-9_])Drill(\d+)")

_PY_README = """# Python code drills

Generated by next-role (`scripts/drills.py generate --language python`).

One file per drill, shared by every part of that drill's series:

    python_drill<N>.py        the class you write (class PythonDrill<N>)
    test_python_drill<N>.py   your pytest tests

Needs pytest once (it is NOT a next-role dependency — next-role only writes
these prompts, it never runs your code):

    pip install pytest

Run them from this directory:

    pytest                       # everything
    pytest test_python_drill1.py # one drill

Flat on purpose — no package, no `__init__.py`, no config. pytest's default
import mode puts this directory on `sys.path`, so `from python_drill1 import
PythonDrill1` just works. Keep the `test_` prefix on test files or pytest
collects nothing.

Standard library only: a drill must run under a bare interpreter.
"""


def rewrite_identifiers(text: str) -> str:
    """`Drill9` / `Drill9Test` -> `JavaDrill9` / `JavaDrill9Test`. Idempotent."""
    return _IDENT_RE.sub(r"JavaDrill\1", text)


def plan_moves(root: Path) -> list[tuple[Path, Path]]:
    """The top-level entries that belong under `java/`, as (src, dest)."""
    java_root = root / "java"
    moves = []
    for name in ("pom.xml", "src", "target"):
        src = root / name
        if src.exists() and not (java_root / name).exists():
            moves.append((src, java_root / name))
    return moves


def plan_renames(root: Path) -> list[tuple[Path, Path]]:
    """Java sources still on the old `Drill<N>` naming, as (src, dest)."""
    java_root = root / "java"
    base = java_root if java_root.is_dir() else root
    out = []
    for rel in ("src/main/java/drills", "src/test/java/drills"):
        pkg = base / rel
        if not pkg.is_dir():
            continue
        for f in sorted(pkg.glob("Drill*.java")):
            new_name = rewrite_identifiers(f.stem) + f.suffix
            if new_name != f.name:
                out.append((f, f.with_name(new_name)))
    return out


def plan_store_edits(drills: list) -> list[dict]:
    """Per-part store fields whose stored CODE still names the old classes."""
    edits = []
    for d in drills:
        if drill_language_of(d) != "java":
            continue
        for p in (d.get("parts") or []):
            att = p.get("attempt") or {}
            for key in ("impl", "test"):
                cur = att.get(key)
                if cur and rewrite_identifiers(cur) != cur:
                    edits.append({"number": d.get("number"),
                                  "part": p.get("part"),
                                  "field": f"attempt.{key}",
                                  "hits": len(_IDENT_RE.findall(cur))})
            sol = (p.get("solution") or {}).get("text")
            if sol and rewrite_identifiers(sol) != sol:
                edits.append({"number": d.get("number"), "part": p.get("part"),
                              "field": "solution.text",
                              "hits": len(_IDENT_RE.findall(sol))})
    return edits


def apply_store_edits(drills: list) -> int:
    """Rewrite the stored code fields in place. Returns fields changed."""
    changed = 0
    for d in drills:
        if drill_language_of(d) != "java":
            continue
        for p in (d.get("parts") or []):
            att = p.get("attempt") or {}
            for key in ("impl", "test"):
                cur = att.get(key)
                if cur:
                    new = rewrite_identifiers(cur)
                    if new != cur:
                        att[key] = new
                        changed += 1
            sol = p.get("solution") or {}
            if sol.get("text"):
                new = rewrite_identifiers(sol["text"])
                if new != sol["text"]:
                    sol["text"] = new
                    changed += 1
    return changed


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Migrate the drills project to the per-language layout.")
    ap.add_argument("--apply", action="store_true",
                    help="Actually make the changes (default: dry run).")
    args = ap.parse_args()

    root = MANUAL_CODE_DRILLS_DIR
    if not root.is_dir():
        print(f"ERROR: drills project not found at {root}")
        sys.exit(1)

    java_root = root / "java"
    py_root   = root / drill_lang("python").subdir
    moves     = plan_moves(root)
    renames   = plan_renames(root)
    drills    = load_drills()
    edits     = plan_store_edits(drills)
    need_py   = not py_root.is_dir()

    print(f"Drills project: {root}")
    print(f"{'APPLY' if args.apply else 'DRY RUN'}\n")

    print(f"1. Move into java/            : {len(moves)} entry(ies)")
    for src, dest in moves:
        print(f"     {src.name} -> java/{dest.name}")
    print(f"2. Create python/            : {'yes' if need_py else 'already exists'}")
    print(f"3. Rename Java sources       : {len(renames)} file(s)")
    for src, dest in renames:
        print(f"     {src.name} -> {dest.name}")
    print(f"4. Rewrite stored code       : {len(edits)} field(s)")
    for e in edits:
        print(f"     drill {e['number']} part {e['part']} {e['field']} "
              f"({e['hits']} reference(s))")

    if not (moves or renames or edits or need_py):
        print("\nNothing to do — already migrated.")
        return

    if not args.apply:
        print("\nDry run. Re-run with --apply to make these changes.")
        return

    # 1. Move the Maven project under java/.
    java_root.mkdir(parents=True, exist_ok=True)
    for src, dest in moves:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dest))
        print(f"Moved {src.name} -> {dest.relative_to(root)}")

    # 2. Scaffold python/.
    py_root.mkdir(parents=True, exist_ok=True)
    readme = py_root / "README.md"
    if not readme.exists():
        readme.write_text(_PY_README, encoding="utf-8")
        print(f"Created {readme.relative_to(root)}")

    # 3. Rename + rewrite the Java sources. Recomputed after the move so the
    #    paths point at their new home.
    for src, dest in plan_renames(root):
        body = src.read_text(encoding="utf-8", errors="replace")
        dest.write_text(rewrite_identifiers(body), encoding="utf-8")
        src.unlink()
        print(f"Renamed {src.name} -> {dest.name} (identifiers rewritten)")

    # 4. Rewrite the stored attempt snapshots + reference solutions.
    changed = apply_store_edits(drills)
    if changed:
        save_drills(drills)
        print(f"Rewrote {changed} stored code field(s) in "
              f"{DRILLS_STORE_PATH.name}")

    print("\nDone. Verify with:  cd java && mvn -q test-compile")


if __name__ == "__main__":
    main()
